# Generated by Django 4.1.1 on 2022-11-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='eventName',
            field=models.CharField(max_length=75),
        ),
    ]
