# Generated by Django 4.1.1 on 2022-10-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('PhoneNumber', models.IntegerField()),
                ('Married', models.BooleanField()),
                ('Birthday', models.DateTimeField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
