# Generated by Django 4.1.1 on 2022-10-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_married'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='PhoneNumber',
            new_name='Age',
        ),
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
