# Generated by Django 4.1.1 on 2022-10-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_image_foreign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreign',
            old_name='Author',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Age',
        ),
        migrations.AddField(
            model_name='foreign',
            name='Age',
            field=models.IntegerField(default=0),
        ),
    ]
