# Generated by Django 4.1.1 on 2022-10-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_author_foreign_user_remove_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
