# Generated by Django 4.1.1 on 2022-10-28 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
