# Generated by Django 4.1.1 on 2022-11-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_myuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
