# Generated by Django 4.1.1 on 2022-11-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_myuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
    ]
